kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
# 1 control plane node and 1 workers
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 31000
    hostPort: 80
    listenAddress: "0.0.0.0"
- role: worker
